### ISSUE TITLE
Transfer exist projects in solutions to .NET Core

### ISSUE THREAD

**Issue by ygolovkin** [acacode/RCOS#6]
@js2me 
Which version we go to use?

**Comment by js2me** [comment]
@ygolovkin I'm not sure, but I think better if we will use latest version

**Comment by ygolovkin** [comment]
@js2me Sure, but should we use preview version?

**Comment by js2me** [comment]
@ygolovkin let's continue conversation in slack 
Because its issue topic which not supposed to conversations
https://acacode.slack.com/messages/CJUJSS37H/apps/A0F81FP4N/
